/**
 * Checks for failed steps in the merged-output.json generated by the generateHtml.js after Cucumber has finished running
 * all tests. It is used in the Jenkins pipeline to determine if any of the test failed so that we can set the build
 * status to failed.
 */
let mergedOutputJson = require('../reports/combined/merged-output.json');

for (let index of mergedOutputJson) {
    let tempIndex = index;
    for (let index of tempIndex.elements[0].steps) {
        if(index.result.status === 'failed'){
            process.exit(1);
        }
    }
}
