/**
 * Checks for failed steps in the merged-output.json generated by the generateHtml.js after Cucumber has finished running
 * all tests. It is used in the Jenkins pipeline to determine if any of the test failed so that we can set the build
 * status to failed.
 */

var mergedOutputJson = require('../reports/combined/merged-output.json');

for (var i = 0; i < mergedOutputJson.length; i++) {

    for (var j = 0; j < mergedOutputJson[i].elements[0].steps.length; j++) {

        if(mergedOutputJson[i].elements[0].steps[j].result.status === 'failed'){
            process.exit(1);
        }
    }
}